spdx/tools-python

spdx/file.py
spdx/package.py

And use a file's SHA1, if present, in package verification code
calculation.

Allow to create a file with pre-calculated SHA1

---

circle.yml

The default machine step calls virtualenv, which is not installed. Doh!

Fix CircleCI integration, and test all CI

---

tests/test_builder.py

Before:
```
./configure
source ./bin/activate
pip install pytest pytest-cov pytest-xdist
pytest --cov=spdx tests
```
Results in `spdx` not found, then `test_utils` not found
After:
The command sequence above runs fine and reports coverage
Signed-off-by: Aleksandr Lisianoi <all3fox@gmail.com>

Add transparent pytest support

---

data/SPDXRdfExample.rdf
data/SPDXSimpleTag.tag
data/SPDXTagExample.tag
spdx/parsers/builderexceptions.py
spdx/parsers/rdfbuilders.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/version.py
tests/test_builder.py
tests/test_document.py
tests/test_tag_value_parser.py

Do not require the SPDX version to be 1.2 #53

---

spdx/parsers/lexers/tagvalue.py
tests/test_tag_value_parser.py

This occurs due to the method `t_text_end` in the
file `lexers\tagvalue.py`. The line `t.value.count('\n')`
doesn't detect newlines because the earlier line is stripped
of whitespaces and newlines. This issue is resolved by first
counting the no. of newline chars and then stripping
whitespaces and newlines so information is preserved.
Closes https://github.com/spdx/tools-python/issues/77

Report correct line no.s while showing errors #77

---

spdx/parsers/tagvalue.py
tests/test_tag_value_parser.py

The cause of the error was the method ​`p_unknown_tag`
in `parsers/tagvalue.py`. Due to the incorrect context-free grammar specification defined in the method, the line after the `unknown_tag` was not taken into consideration. The
context-free grammar specification was rectified and tests
were corresponding tests were added.

Report an error when `UNKNOWN_TAG` is found #55

---

data/SPDXRdfExample.rdf
data/SPDXSimpleTag.tag
data/SPDXTagExample.tag
spdx/document.py
spdx/file.py
spdx/parsers/lexers/tagvalue.py
spdx/parsers/rdf.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/parsers/validations.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
tests/data/doc_write/rdf-simple-plus.json
tests/data/doc_write/rdf-simple.json
tests/data/doc_write/tv-simple-plus.tv
tests/data/doc_write/tv-simple.tv
tests/test_document.py
tests/test_tag_value_parser.py

Upgrade the 'File' class to the SPDX 2.1 specification

---

data/SPDXRdfExample.rdf
data/SPDXTagExample.tag
examples/parse_rdf.py
spdx/annotation.py
spdx/document.py
spdx/parsers/lexers/tagvalue.py
spdx/parsers/rdf.py
spdx/parsers/rdfbuilders.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/parsers/validations.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
tests/test_builder.py
tests/test_conversion.py

Add 'annotator','annotation_date', and 'comment'
to the 'annotation' class.

Add 'Annotation' class as a part of the SPDX 2.1 specification.

---

spdx/parsers/tagvaluebuilders.py

Made the following change in parsers/tagvaluebuilders.py:
Replaced the string `Sets the package's license comment` by `Sets the package's copyright text` for the method set_pkg_cr_text.

change docstring of method set_pkg_cr_text

---

spdx/parsers/validations.py

@pombredanne I have fixed the `TypeError` but while parsing `sample.tag` file it still gives an error `Only one PackageHomePage allowed, extra at line: 21` although there is only one key with `PackageHomePage` in the whole document.
PR for issue #39 
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

Fix TypeError while parsing .tag file #39

---

data/SPDXRdfExample.rdf
data/SPDXTagExample.tag
spdx/document.py
spdx/parsers/lexers/tagvalue.py
spdx/parsers/rdf.py
spdx/parsers/rdfbuilders.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/parsers/validations.py
spdx/snippet.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
tests/test_builder.py
tests/test_tag_value_parser.py

This is to add 'Snippet' class as a part of the SPDX 2.1 specification
This is https://github.com/spdx/tools-python/pull/76 from @yash-nisar rebased by @xavierfigueroav

Add 'Snippet' class as a part of the SPDX 2.1 specification

---

spdx/parsers/rdf.py
tests/test_rdf_parser.py

Fixes #97
The field Document.extracted_licenses contained duplicate ExtractedLicense objects when they are parsed from RDF files. Both extracted licenses in `<licenseConcluded>` and `<licenseDeclared>` were being added twice.
This PR makes extracted licenses are parsed only once, when `<SpdxDocument>` is being parsed.
Signed-off-by: Xavier Figueroa <xavierfigueroav@gmail.com>

Fix #97 Duplicate extracted licenses when parsing from RDF

---

spdx/config.py
tests/test_config.py

Fix #102 
This PR modifies config.py file to use the method `from_str` in `Version` instead of creating the object directly with string values.
Signed-off-by: Xavier Figueroa <xavierfigueroav@gmail.com>

Fix #102 by using Version method from_str in config.py file.

---

data/SPDXRdfExample.rdf
spdx/parsers/rdf.py
tests/data/doc_parse/spdx-expected.json
tests/test_rdf_parser.py
tests/utils_test.py

1. About fixing:
- Pass all rdflib types in RDF parsers into six.text_type function before passing them into RDF builders.
2. About tests:
- Add test utilities that build a Python dictionary representation of the information stored in models.
- Add a JSON file with expected info after parsing a test file.
- Add tests that open a test file, open the expected file and compare them.
Signed-off-by: Xavier Figueroa <xavierfigueroav@gmail.com>

 Fix #91 by passing all rdflib types in six.text_type function

---

data/SPDXTagExample.tag
spdx/parsers/tagvalue.py

add PackageHomePage tag to SPDXTagExample.tag
Signed-off-by: Andreas Kleber <andreas@drosselweg7a.de>

Fix parsing of PackageHomePage (was probably a copy and past error),

---

.circleci/config.yml
setup.py

Signed-off-by: Shubham Kumar Jha <skjha832@gmail.com>
Fixes #140 
Build failures were occurring in Python2 due to `rdflib` allowing any version of `pyparsing` (it's dependency) to be installed. It eventually installs the latest version which doesn't work with Python 2.7.
Fix:
* Updated setup.py file to install pyparsing <= 1.5.7 when installed with Python 2.7
* Since, rdflib allows any version of pyparsing to be installed, the latest version is not installed.

Fixes the install error in Python 2.7 and CircleCI error with Python 3.4.8

---

data/SPDXRdfExample.rdf

Previously, there was an extra '>' in line 42 which was the reason this rdf/xml file was showing error. Now, the file is validated.

Validated the RDF file

---

spdx/document.py
spdx/parsers/jsonyamlxmlbuilders.py
spdx/parsers/rdfbuilders.py
spdx/parsers/tagvaluebuilders.py
spdx/writers/jsonyamlxml.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
tests/test_builder.py
tests/test_document.py

This set of patches adds support for multiple packages per document, by adding document.packages as an array.  The API for managing multiple packages is set up to mimic the other APIs for managing multiple objects (files, external licenses, etc.).
To preserve backwards compatibility, this patch introduces document.package as a property; this property is implemented using document.packages behind the scenes, and triggers a DeprecationWarning.
Support is included for parsing documents with multiple packages, as well as writing such documents.
Fixes #79.

Support multiple packages per SPDX document.

---

examples/write_tv.py

I've been fiddling with the python library lately. I found a couple of little
hiccups in the write_tv example. I'm opening this PR so I don't forget,
although I'll admit I haven't done my due dilligence figuring out if this
example is in fact already fixed somewhere else (and apologies for that!).
Also, the spdx_id fields that I chose may prove to be not entirely compliant,
as I just read the validation code and  picked something that passed...

Fix write_tv example

---

appveyor.yml

https://www.appveyor.com/docs/build-environment/ : says 2015 is the default
https://www.appveyor.com/docs/windows-images-software/ : says 3.9 is only on 2019

python3.9 is only present on 2019 images which is not the default

---

examples/pp_tv.py
examples/write_tv.py
spdx/annotation.py
spdx/creationinfo.py
spdx/document.py
spdx/file.py
spdx/package.py
spdx/parsers/jsonyamlxml.py
spdx/parsers/loggers.py
spdx/parsers/rdf.py
spdx/parsers/tagvalue.py
spdx/relationship.py
spdx/review.py
spdx/snippet.py
spdx/tv_to_rdf.py
spdx/writers/json.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
spdx/writers/xml.py
spdx/writers/yaml.py
tests/test_conversion.py
tests/test_document.py
tests/test_error_messages.py

There are a lot of 
```
messages = messages + ["ExternalPackageRef has no category."]
```
in this codebase..
This is not very pythonic, and does not contain much context information, which makes it difficult to understand what part of the 8MB spdx dump file generated by proprietary tool is not recognised.
This is a first simple code to start discussion on the problematic.
Will integrate in the rest of the code when we agree on the API.

introduce message handler

---

spdx/package.py
spdx/parsers/jsonparser.py
spdx/parsers/jsonyamlxml.py
spdx/parsers/parse_anything.py
spdx/parsers/tagvaluebuilders.py
spdx/parsers/validations.py
spdx/parsers/yamlparser.py
spdx/writers/rdf.py
tests/data/doc_parse/SBOMexpected.json
tests/data/doc_parse/expected.json
tests/data/doc_parse/spdx-expected.json
tests/data/formats/SPDXSBOMExample.spdx.yml
tests/test_jsonyamlxml_parser.py
tests/test_parse_anything.py
tests/test_rdf_parser.py
tests/test_write_anything.py
tests/utils_test.py

example taken from https://github.com/spdx/spdx-spec/issues/439
coming from ART people
I came into some of the issues of #180 like multiple package support and pkgFilesAnalyzed, so it will probably override it.

add spdxlite 2.2 SBOM parsing support

---

.circleci/config.yml
appveyor.yml

Signed-off-by: Rodney Richardson <rodney.richardson@cambridgeconsultants.com>
Fixes #204

Remove python 3.6 support, and add python 3.10.

---

spdx/parsers/parse_anything.py
spdx/parsers/tagvaluebuilders.py
tests/data/formats/SPDXSBOMExample.tag
tests/test_write_anything.py

fixes #222 
I also added a new testfile so that parsing of TV-files with multiple packages is also tested. The new testfile needs to be skipped in the [test_write_anything.py](https://github.com/spdx/tools-python/blob/main/tests/test_write_anything.py) since conversion of SPDX 2.2 files is not implemented yet and yields to failures of the test.  
This PR also fixes parsing of .spdx files which were parsed as .rdf files before. 

[issue-222] fix parsing of tv-files with multiple packages

---

spdx/file.py
spdx/package.py
spdx/parsers/jsonyamlxml.py
spdx/parsers/rdf.py
spdx/parsers/tagvaluebuilders.py
spdx/snippet.py
spdx/writers/jsonyamlxml.py
tests/test_document.py

fixes #272
only checked and adapted the jsonyamlxml workflow

Make 2.3 optional properties optional

---

spdx/parsers/jsonyamlxml.py
spdx/writers/jsonyamlxml.py
tests/data/doc_parse/expected.json
tests/data/formats/SPDXJsonExample.json
tests/data/formats/SPDXXmlExample.xml
tests/data/formats/SPDXYamlExample.yaml

fixes #275
With this PR annotations are attached to the spdx element according to the `annotations.spdx_id` field. Annotations  that refer to external SPDX Elements aren't written as this is currently not allowed in the [json-spec](https://github.com/spdx/spdx-spec/blob/810d229fed8093aae03d9dd42aa0a8174611121a/schemas/spdx-schema.json#L11-L37).

serialize/ deserialize annotations 

---

spdx/annotation.py
spdx/parsers/lexers/tagvalue.py
spdx/parsers/tagvalue.py
tests/test_tag_value_parser.py

Fixes the error described in #196 for parsing the annotation type in tv-files.
I also added two tests to verify that annotations are parsed correctly.

[tv-parser] fix parsing of annotation type

---

spdx/parsers/jsonyamlxml.py
spdx/parsers/xmlparser.py
spdx/writers/jsonyamlxml.py
tests/data/doc_parse/expected.json
tests/data/doc_parse/spdx-expected.json
tests/data/formats/SPDXJsonExample.json
tests/data/formats/SPDXXmlExample.xml
tests/data/formats/SPDXYamlExample.yaml
tests/test_write_anything.py
tests/utils_test.py

fixes #287 
also adds an additional `licenseInfoInSnippet` for the tests

Rename snippet properties

---

src/model/actor.py
src/model/annotation.py
src/model/checksum.py
src/model/document.py
src/model/external_document_ref.py
src/model/extracted_licensing_info.py
src/model/file.py
src/model/license.py
src/model/license_expression.py
src/model/package.py
src/model/relationship.py
src/model/snippet.py
src/model/spdx_no_assertion.py
src/model/spdx_none.py
src/model/version.py
tests/model/test_license.py
tests/model/test_version.py

Fixes https://github.com/spdx/tools-python/issues/290
Rewritten data model, hopefully clearer in particular with regards to types. It's fairly minimal so far, we can add more utility later (e.g. more magic functions)
Note: As soon as the Python min version is officially 3.7, we can check whether [dataclasses](https://docs.python.org/3/library/dataclasses.html) can reduce some of the annoying duplication involved in writing constructors, for example.

[issue-290] refactor data model

---

spdx/parsers/builderexceptions.py
spdx/parsers/rdfbuilders.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/parsers/validations.py
spdx/writers/tagvalue.py
tests/data/doc_write/json-simple-plus.json
tests/data/doc_write/json-simple.json
tests/data/doc_write/rdf-simple-plus.json
tests/data/doc_write/rdf-simple.json
tests/data/doc_write/tv-simple-plus.tv
tests/data/doc_write/tv-simple.tv
tests/data/doc_write/xml-simple-plus.xml
tests/data/doc_write/xml-simple.xml
tests/data/doc_write/yaml-simple-plus.yaml
tests/data/doc_write/yaml-simple.yaml
tests/data/formats/SPDXSimpleTag.tag
tests/data/formats/SPDXTagExample.tag
tests/test_builder.py
tests/test_document.py

[issue-299] allow single line of text in free form text

---

spdx/creationinfo.py
spdx/document.py
spdx/package.py
spdx/parsers/jsonyamlxml.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
spdx/utils.py
spdx/writers/jsonyamlxml.py
spdx/writers/rdf.py
spdx/writers/tagvalue.py
tests/data/doc_parse/SBOMexpected.json
tests/data/doc_parse/expected.json
tests/data/doc_parse/spdx-expected.json
tests/data/doc_write/rdf-simple-plus.json
tests/data/doc_write/rdf-simple.json
tests/data/formats/SPDXTagExample.tag
tests/test_conversion.py
tests/test_document.py
tests/test_jsonyamlxml_writer.py
tests/test_package.py
tests/test_rdf_parser.py
tests/test_rdf_writer.py
tests/test_tag_value_parser.py
tests/test_write_anything.py
tests/utils_test.py

This PR is still in progress but attempts to fix #181.
also fixes #297 

[issue-181] add files at document-level

---

spdx/cli_tools/parser.py

[issue-326] fix output for licenses that are SPDXNone or NoAssert-objects

---

spdx/parsers/jsonyamlxmlbuilders.py

[issue-328] jsonyamlxml: fix parsing of file copyright text

---

spdx/parsers/jsonyamlxml.py
spdx/parsers/xmlparser.py
spdx/writers/jsonyamlxml.py
tests/data/formats/SPDXJsonExample.json
tests/data/formats/SPDXXmlExample.xml
tests/data/formats/SPDXYamlExample.yaml

Fixes https://github.com/spdx/tools-python/issues/344
Signed-off-by: Nicolaus Weidner <nicolaus.weidner@tngtech.com>

[issue-344] rename seeAlso to seeAlsos in json/yaml/xml

---

spdx/creationinfo.py
spdx/document.py

I decided to keep the input argument for `license_list_version` for the `document` object for backwards compatibility and redirect the input to the `creation_info` field. The current parsers and writers only use the `license_list_version` field from the `creation_info` so nothing needs to be changed here.

[issue-243] delete duplicated license list version field

---

src/model/extracted_licensing_info.py
tests/model/test_extracted_licensing_info.py

this makes sense as it is the only unconditionally optional parameter (also, it is the order as found in the specification)

[refactor] move comment to the end of extractedLicensingInfo constructor

---

pyproject.toml
tox.ini

e6daf69 created a dependency on setuptools>=61.2,
and setuptools v59.7.0 removed Python 3.6 support.

Require Python 3.7

---

src/model/typing/constructor_type_errors.py
src/parser/error.py
src/parser/json/actor_parser.py
src/parser/json/annotation_parser.py
src/parser/json/checksum_parser.py
src/parser/json/creation_info_parser.py
src/parser/json/dict_parsing_functions.py
src/parser/json/extracted_licensing_info_parser.py
src/parser/json/extracted_licensing_parser.py
src/parser/json/file_parser.py
src/parser/json/json_parser.py
src/parser/json/license_expression_parser.py
src/parser/json/package_parser.py
src/parser/json/relationship_parser.py
src/parser/json/snippet_parser.py
src/parser/logger.py
tests/parser/test_actor_parser.py
tests/parser/test_annotation_parser.py
tests/parser/test_checksum_parser.py
tests/parser/test_creation_info_parser.py
tests/parser/test_dict_parsing_functions.py
tests/parser/test_extracted_licensing_info_parser.py
tests/parser/test_file_parser.py
tests/parser/test_json_parser.py
tests/parser/test_license_expression_parser.py
tests/parser/test_package_parser.py
tests/parser/test_relationship_parser.py
tests/parser/test_snippet_parser.py

[Issue 305] add new json parser

---

src/model/relationship.py
src/parser/json/relationship_parser.py
src/validation/relationship_validator.py
tests/model/test_relationship.py
tests/parser/test_relationship_parser.py
tests/validation/test_relationship_validator.py

[issue-389] allow NONE and NOASSERTION in related_spdx_element_id

---

src/validation/creation_info_validator.py
src/validation/document_validator.py
src/validation/relationship_validator.py
src/writer/json/json_writer.py
tests/validation/test_creation_info_validator.py
tests/validation/test_document_validator.py
tests/validation/test_relationship_validator.py

[issue-403] change spdx version handling during validation

---

src/jsonschema/document_converter.py
src/jsonschema/document_properties.py
src/parser/jsonlikedict/package_parser.py
src/parser/xml/xml_parser.py
tests/jsonschema/test_document_converter.py
tests/writer/json/expected_results/expected.json

While testing I came upon two bugs:
- `hasExtractedLicensingInfo` must be `hasExtractedLicensingInfos`
- parsing of `filesAnalyzed` failed because of its boolean nature the `if not value: return default` triggered for `filesAnalyzed=False`

Minor parsing/writing fixes

---

.circleci/config.yml

add dummy config.yml to pass pipeline

---

src/spdx/parser/jsonlikedict/json_like_dict_parser.py
src/spdx/validation/creation_info_validator.py
tests/parser/jsonlikedict/test_dict_parsing_functions.py
tests/writer/json/expected_results/expected.json
tests/writer/json/test_json_writer.py
tests/writer/tagvalue/test_package_writer.py
tests/writer/tagvalue/test_tagvalue_writer.py

Addition to #409: Use fixtures in writer tests and enable validation in test_write_json (fixes TODO comment). The second commit deltes unused imports, which is only a minor fix and therefore doesn't need its own PR.

[issue-397] use fixtures in writer tests

---

tests/model/test_creation_info.py
tests/model/test_document.py
tests/model/test_package.py

[issue-420] fix order of mocks to match input arguments

---

src/spdx/jsonschema/file_converter.py
src/spdx/jsonschema/snippet_converter.py
src/spdx/model/file.py
src/spdx/model/snippet.py
src/spdx/parser/jsonlikedict/file_parser.py
src/spdx/parser/jsonlikedict/snippet_parser.py
src/spdx/validation/file_validator.py
src/spdx/validation/snippet_validator.py
src/spdx/writer/tagvalue/file_writer.py
src/spdx/writer/tagvalue/snippet_writer.py
tests/fixtures.py
tests/jsonschema/test_file_converter.py
tests/jsonschema/test_snippet_converter.py
tests/model/test_file.py
tests/model/test_snippet.py
tests/parser/jsonlikedict/test_file_parser.py
tests/parser/jsonlikedict/test_snippet_parser.py
tests/writer/json/expected_results/expected.json

[issue-392] make usage of license_concluded consistent

---

src/spdx/clitools/pyspdxtools.py

also print validation output to stderr
fixes #442

[issue-442] change CLI to read version from document

---

spdx/package.py
spdx/parsers/jsonyamlxml.py

fixes #449 
I tried to add a test for this but as the builder and parser are quite nested and I couldn't really isolate this function, I gave up. If you think it is necessary to add a test here, I would simply adapt the [testfile](https://github.com/spdx/tools-python/blob/main/tests/data/formats/SPDXJsonExample.json). 

[issue-449] fix parsing of package supplier and package originator

---

src/spdx/validation/external_package_ref_validator.py
src/spdx/validation/uri_validators.py
tests/spdx/validation/test_creation_info_validator.py
tests/spdx/validation/test_uri_validators.py

also make swid accept non-absolute URIs as I did not find information on that this would be forbidden
fixes #457 

[issue-457] add "no #" requirement to validation messages

---

src/spdx/validation/document_validator.py
tests/spdx/validation/test_document_validator.py

[issue-378] implement invalidation of duplicated SPDX Ids

---

src/spdx/validation/spdx_id_validators.py
tests/spdx/validation/test_annotation_validator.py
tests/spdx/validation/test_relationship_validator.py
tests/spdx/validation/test_spdx_id_validators.py

also fix some strings
fixes #376 

[issue-376] add tests for spdx_id_validators

---

tests/spdx/validation/test_document_validator.py

[issue-375] test "document describes at least one element"

---

src/spdx/writer/tagvalue/tagvalue_writer_helper_functions.py
tests/spdx/writer/tagvalue/test_tagvalue_writer_helper_functions.py

check against RelationshipType to let package information precede contained file information and add a test for the helper function 
fixes #466

[issue-466] bug fix and add test

---

src/spdx/writer/rdf/relationship_writer.py
tests/spdx/writer/rdf/test_relationship_writer.py

addition to PR #448 (issue #455) 

[issue-407] write comments for relationships

---

src/spdx/parser/jsonlikedict/dict_parsing_functions.py

The return value of err.args[0] is a string, so we need to use append to add this string to the list of messages in the logger.

fix helper method

---

spdx/parsers/lexers/tagvalue.py
tests/test_tag_value_parser.py

The previous regular expressions for ranges would prevent lines with ":" to be parsed as LINE and instead be parsed as RANGE, the remainder after ":\d+" would be truncated and ignored, this lead to problems when parsing a package version like "1:2.36.1-8+deb11u1".
fixes #479

[issue-479] fix parsing of snippet ranges

---

src/spdx/validation/file_validator.py
src/spdx/validation/license_expression_validator.py
src/spdx/validation/package_validator.py
src/spdx/validation/snippet_validator.py
src/spdx/validation/validation_message.py
tests/spdx/validation/test_license_expression_validator.py

[issue-374] implement license expression validation

---

README.md

[issue-391] update readme to reflect the new usage after refactoring

---

src/spdx/clitools/pyspdxtools.py
src/spdx/parser/rdf/creation_info_parser.py
src/spdx/writer/rdf/writer_utils.py
tests/spdx/parser/rdf/test_creation_info_parser.py

[issue-441] replace print() with logging

---

spdx/parsers/lexers/tagvalue.py
spdx/parsers/tagvalue.py
tests/test_tag_value_parser.py

Without this fix lines that contain a whitespace and a line break were not taken into account when counting the lines. This lead to a mismatch in the line number printed within the error message and the actual falsy line.
Working on this, I saw that the tag value parser was missing two error messages. This seems to be missing from the early states of the repo and it's rather interesting that this never popped up as it could easily cause a `KeyError`.
fixes #465

Issue 465 fix line mismatch

---

tests/data/formats/SPDXJsonExampleEmptyArrays.json
tests/test_write_anything.py

fixed during a review round before 0.7.1 pre-release
the package in the example was duplicated, I erased one of them, making the conversion tests stable

[issue-496] fix SPDXJsonExampleEmptyArrays.json test

---

spdx/parsers/lexers/tagvalue.py
spdx/parsers/tagvalue.py
spdx/parsers/tagvaluebuilders.py
tests/test_builder.py
tests/test_tag_value_parser.py

To be able to also parse package versions that might look like a range, e.g. `1:2` I decided to delete the token `RANGE` from the tag-value parser. The build functions for `SnippetByteRange` and `SnippetLineRange` therefore need to check if the parsed value matches the expected pattern and will raise a `SPDXValueError` if not. Since the tests in `test_builder.py` are wrapped in a class that is inherited from `TestCase` I can't use `pytest.mark.parametrize` and additional parameters for the tests `test_snippet_byte_range_value` and `test_snippet_line_range_value`.

[issue-479] fix parsing of package version that looks like a range value

---

src/spdx/writer/tagvalue/creation_info_writer.py

While working on the parser  for tag-value files I came across this little bug.

[fix] use correct value for LicenseListVersion

---

tests/spdx/writer/rdf/test_creation_info_writer.py

Working on the tag-value parser I got a warning from pytest that lead me to this small bug.

fix creation info writer test

---

spdx/writers/tagvalue.py

Fix #508
This fixes the issue in tag;value format.
I did not check the other formats.

Remove multiple identical LicenseInfoInFile

---

pyproject.toml

We need to add a `py.typed` file to the source directory of the package so that other downstream tools can use the type hints. 
For reference: 
- https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
- https://jugmac00.github.io/blog/bite-my-shiny-type-annotated-library/#poetry

[issue-228] make type hints in code readable for downstream packages

---

src/spdx/writer/tagvalue/creation_info_writer.py
tests/spdx/writer/tagvalue/test_creation_info_writer.py
tests/spdx/writer/tagvalue/test_package_writer.py

Due to the type conversion before entering the `set_value` method a `None` value for `LicenseListVersion` was written to the outptut file. The `f-string` calls the implemented `str`-conversion for the instance of `Version`, so we don't need to do this conversion explicitly. 
To improve the test coverage here, I also added a test.

Fix tag value writer

---

pyproject.toml

typeguard 3.0.0 introduces breaking changes, but so far we are not certain that we need any new features of it.

fix the version of typeguard

---

src/spdx3/bump_from_spdx2/annotation.py
src/spdx3/bump_from_spdx2/file.py
src/spdx3/bump_from_spdx2/package.py
src/spdx3/bump_from_spdx2/relationship.py
src/spdx3/bump_from_spdx2/snippet.py
src/spdx3/bump_from_spdx2/spdx_document.py
src/spdx3/clitools/pyspdxtools3.py
src/spdx3/payload.py
src/spdx3/writer/console/spdx_id_map_writer.py
tests/spdx/fixtures.py
tests/spdx/writer/json/expected_results/expected.json
tests/spdx3/bump/test_file_bump.py
tests/spdx3/bump/test_package_bump.py
tests/spdx3/bump/test_snippet_bump.py
tests/spdx3/bump/test_spdx_document_bump.py

also change `spdx_id_map` to `payload` and fix a bug where `bump_annotation` changed the `creation_info`

[issue-427] adapt bump methods to allow bumping of actors within other elements

---

src/spdx/writer/rdf/rdf_writer.py
src/spdx/writer/tagvalue/tagvalue_writer.py
src/spdx/writer/write_anything.py
src/spdx/writer/xml/xml_writer.py
src/spdx/writer/yaml/yaml_writer.py
tests/spdx/writer/tagvalue/test_tagvalue_writer.py

Reading through the migration guideline I came across the line 
> Now, when calling write_file(), by default a Document will be validated against the specification before it can be written to a file.
which lead me to this addition.
part of #402

[issue-402] add validation option to tag-value writer

---

.github/workflows/install_and_test.yml

As we support Python 3.11 we should also test against it in our GitHub Action.
Additionally I added a push to the branch as a trigger for this workflow. When merging this we will need to adapt this.

Add python 3.11 to GitHub Action

---

src/spdx/parser/tagvalue/lexer.py
src/spdx/parser/tagvalue/parser.py
tests/spdx/parser/tagvalue/test_tag_value_lexer.py

change `DATE` to `ISO8601_DATE`, don't inherit from `object`

small changes to tag-value lexer/parser

---

tests/spdx/test_document_utils.py

[issue-487] add tests for the `document_utils.py` module

---

spdx/writers/rdf.py
tests/data/doc_write/rdf-mini.json
tests/data/doc_write/rdf-simple-plus.json
tests/data/doc_write/rdf-simple.json

Note that this fix won't be merged to main as we are in the process of merging the refactored version to main. This PR will instead be merged to the v.0.7.1 branch. 
fixes #542

[issue-542] use the documents namespace as prefix

---

src/spdx/parser/rdf/extracted_licensing_info_parser.py
src/spdx/parser/rdf/rdf_parser.py
tests/spdx/data/formats/SPDXRdfExample-v2.2.spdx.rdf.xml
tests/spdx/parser/rdf/data/file_to_test_rdf_parser.rdf.xml
tests/spdx/parser/rdf/test_extracted_licensing_info_parser.py
tests/spdx/parser/rdf/test_rdf_parser.py

Use licenseID from extracted licensing info URIRef if no licenseId node is provided.
fixes #547

[issue-547] fix rdf parser

---

README.md

While reading through the README on our repo's main page, I noticed that you have to scroll to read the complete inline comments in the Python example. This should not be an issue anymore, now.

shorten line lengths in README

---

src/spdx3/README.md
src/spdx3/bump_from_spdx2/package.py
src/spdx3/model/software/package.py
src/spdx3/writer/console/software/package_writer.py
tests/spdx3/bump/test_package_bump.py
tests/spdx3/model/software/test_package.py

As defined in https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Package.md.
During bumping, this will be filled with the content of `spdx2_package.version`.

[spdx-3.0] add package_version

---

src/spdx3/bump_from_spdx2/creation_information.py
src/spdx3/model/creation_information.py
src/spdx3/writer/console/creation_information_writer.py
tests/spdx3/model/test_creation_information.py

As seen in https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/CreationInformation.md.
`spdx2_creation_info.document_comment` converts into this.

[SPDX-3.0] add creation_info comment

---

src/spdx/parser/rdf/annotation_parser.py
src/spdx/parser/rdf/checksum_parser.py
src/spdx/parser/rdf/creation_info_parser.py
src/spdx/parser/rdf/extracted_licensing_info_parser.py
src/spdx/parser/rdf/file_parser.py
src/spdx/parser/rdf/graph_parsing_functions.py
src/spdx/parser/rdf/license_expression_parser.py
src/spdx/parser/rdf/package_parser.py
src/spdx/parser/rdf/rdf_parser.py
src/spdx/parser/rdf/relationship_parser.py
src/spdx/parser/rdf/snippet_parser.py
tests/spdx/parser/rdf/data/file_to_test_rdf_parser.rdf.xml
tests/spdx/parser/rdf/test_annotation_parser.py
tests/spdx/parser/rdf/test_checksum_parser.py
tests/spdx/parser/rdf/test_creation_info_parser.py
tests/spdx/parser/rdf/test_file_parser.py
tests/spdx/parser/rdf/test_package_parser.py
tests/spdx/parser/rdf/test_rdf_parser.py
tests/spdx/parser/rdf/test_relationship_parser.py
tests/spdx/parser/rdf/test_snippet_parser.py

This PR adds some logic to parse implicit "hasFiles" and "describesPackage" relationships. 
fixes #561

[issue-561] fix rdf parser

---

src/spdx3/bump_from_spdx2/package.py
tests/spdx3/bump/test_package_bump.py

The package URL migration become even more complex, [see here](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.r889hoh0obeu).
That is, a purl is converted to the new SPDX3 packageUrl property iff it is the only purl and has no comment.

[issue-427] add purl special case with comment distinction

---

.github/workflows/install_and_test.yml
CONTRIBUTING.md
pyproject.toml
tests/spdx/test_graph_generation.py

I decided to add the installation of the optional dependency and the test as additional steps to the GitHub Action so that we ensure on the one hand that the source installation is successful und all tests pass (resp. are skipped) and on the other hand also run the tests for the optional feature. 
addition to #562, fixes #558
Edit: I updated the test to only be skipped if `networkx` is not installed and install this package manually in the GitHub Action, as this is the only package needed for the tests. `pygraphviz` requires an installation of `graphviz` on the operating system. This seems to be more involving for Windows so I decided not to add this for the moment, as this is only an optional feature.

[issue-558] add test for optional feature to GitHub Action

---

src/spdx/writer/json/json_writer.py
src/spdx/writer/write_anything.py
tests/spdx/writer/json/test_json_writer.py

part of #402 
This will make it consistent with the other functions of other formats.

[issue-402] change `write_document()` to `write_document_to_file()`

---

src/spdx/validation/document_validator.py
tests/spdx/validation/test_document_validator.py

The new logic is now: 
A `DESCRIBES` relationship is not mandatory if there is only a single SPDX element present which is a package.

[issue-540] change DESCRIBES validation

---

README.md
src/spdx/jsonschema/document_converter.py
src/spdx/jsonschema/document_properties.py
src/spdx/jsonschema/package_converter.py
src/spdx/jsonschema/package_properties.py
tests/spdx/jsonschema/test_document_converter.py
tests/spdx/jsonschema/test_package_converter.py
tests/spdx/writer/json/expected_results/expected.json

Remove `documentDescribes` and `hasFiles` from json output

---

src/spdx/clitools/pyspdxtools.py
tests/spdx/test_cli.py

With this PR we make infile a required argument to display a help message when no arguments are given.
I also added some test to check that the cli fails for invalid arguments and passes for correct arguments.
fixes #586

[issue-586] fix CLI

---

README.md

[issue-593] add imports to README example

---

README.md
examples/spdx2_document_from_scratch.py

[issue-593] add spdx2_document_from_scratch example

---

.flake8

This matches isort skipping these files.

make flake8 ignore all __init__.py

---

src/spdx_tools/spdx3/bump_from_spdx2/annotation.py
src/spdx_tools/spdx3/bump_from_spdx2/creation_information.py
src/spdx_tools/spdx3/bump_from_spdx2/external_document_ref.py
src/spdx_tools/spdx3/bump_from_spdx2/file.py
src/spdx_tools/spdx3/bump_from_spdx2/package.py
src/spdx_tools/spdx3/bump_from_spdx2/relationship.py
src/spdx_tools/spdx3/bump_from_spdx2/snippet.py

While going through the bumping modules, I had the urge to utilize the new black formatting a bit more and make the assignment of SPDX 2 to 3 properties a bit more comprehensible (hopefully). Now, for properties that just carry over 1-to-1, you don't have to look around in the module anymore to find the initialization of these variables.

refactor bumping modules

---

src/spdx_tools/spdx3/bump_from_spdx2/package.py
tests/spdx3/bump/test_package_bump.py

If originator is NOASSERTION or not provided we don't need to call `bump_actor`.
subtask of #602

[issue_602] fix package bump 

---

tests/spdx/data/SPDXXMLExample-v2.3.spdx.xml
tests/spdx/data/SPDXYAMLExample-v2.3.spdx.yaml

I noticed that these two example files are marked as invalid. The changed files align with the examples given in the spdx-spec repo. As far as I understand the spec we only add the documents namespace to `referenceType` in `RDF` format, not in any other. So I think the examples were simply incorrect and there is no need to adapt the code to accept these kind of `referenceType`.

make example files valid

---

src/spdx_tools/spdx/parser/rdf/creation_info_parser.py
src/spdx_tools/spdx/parser/rdf/rdf_parser.py
tests/spdx/parser/rdf/data/invalid_documents/invalid_creation_info.rdf.xml
tests/spdx/parser/rdf/data/invalid_documents/invalid_creation_info_with_snippet.rdf.xml
tests/spdx/parser/rdf/test_creation_info_parser.py

This PR fixes two things:
- If there is any error while parsing the creation info  the parsing process will be canceled as the following code tries to access `creation_info.doc_namespace`. This lead to an uncaught `AttributeError`. 
- If there are no creators in the given input file an `SPDXParsingError` will be raised as this is not valid.
I added two negative tests for these cases. They seem to be pretty similar but they test different things. I added the `invalid_creation_info_with_snippet` to verify that there is no uncaught error whereas the other test simply tests that a file without creators will raise an `SPDXParsingError`. 
fixes #615

Issue 615 fix rdf parser

---

pyproject.toml

Per default, pytest skips over folder containing "build". This overwrites that default.

Make pytest not skip 'test_build' folders

---

README.md

I adapted the wiki and forgot to update the link in the README.md. This PR fixes the link.

fix link to migration guide

---

src/spdx_tools/spdx3/bump_from_spdx2/relationship.py
src/spdx_tools/spdx3/bump_from_spdx2/spdx_document.py
src/spdx_tools/spdx3/writer/console/payload_writer.py
tests/spdx3/bump/test_relationship_bump.py

This PR is based on #609.  
I assumed that relationships with the same "from spdx_id"  and relationship_type should be merged. Sone conversions are not yet defined or the RelatoinshipType doesn't exist yet in the spdx-3-model and the prototype, I decided to print an info about missing conversions here and added a comment at the corresponding relationshiptypes. 
fixes #602

[issue_602] update relationship bump

---

.github/workflows/install_and_test.yml
pyproject.toml
src/spdx_tools/spdx3/validation/json_ld/shacl_validation.py
src/spdx_tools/spdx3/writer/json_ld/json_ld_converter.py
src/spdx_tools/spdx3/writer/json_ld/json_ld_writer.py
src/spdx_tools/spdx3/writer/json_ld/owl_to_context.py
src/spdx_tools/spdx3/writer/json_ld/process.md
tests/spdx3/validation/json_ld/test_shacl_validation.py

This PR updates the generated `context.json` and `SPDX_OWL.json` and adds documentation on how these files were created. Additionally a small bug in the serialization to json-ld is fixed - the property for relationships need to be `from` not `fromElement`. 
This PR is baed on #625 and needs to be rebased once #625 is merged. Only the last two commits are relevant here.

Update generated files and add documentation

---

src/spdx_tools/spdx3/model/agent.py
src/spdx_tools/spdx3/model/ai/ai_package.py
src/spdx_tools/spdx3/model/annotation.py
src/spdx_tools/spdx3/model/bom.py
src/spdx_tools/spdx3/model/build/build.py
src/spdx_tools/spdx3/model/bundle.py
src/spdx_tools/spdx3/model/dataset/dataset.py
src/spdx_tools/spdx3/model/element.py
src/spdx_tools/spdx3/model/lifecycle_scoped_relationship.py
src/spdx_tools/spdx3/model/organization.py
src/spdx_tools/spdx3/model/person.py
src/spdx_tools/spdx3/model/relationship.py
src/spdx_tools/spdx3/model/security/cvss_v2_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/cvss_v3_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/epss_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/exploit_catalog_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/ssvc_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/vex_affected_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/vex_fixed_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/vex_not_affected_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/vex_under_investigation_vuln_assessment_relationship.py
src/spdx_tools/spdx3/model/security/vulnerability.py
src/spdx_tools/spdx3/model/software/file.py
src/spdx_tools/spdx3/model/software/package.py
src/spdx_tools/spdx3/model/software/sbom.py
src/spdx_tools/spdx3/model/software/snippet.py
src/spdx_tools/spdx3/model/software/software_dependency_relationship.py
src/spdx_tools/spdx3/model/software_agent.py
src/spdx_tools/spdx3/model/spdx_document.py
src/spdx_tools/spdx3/model/tool.py

This changes the type of `extension` to `Optional[str]`.
fixes https://github.com/spdx/tools-python/issues/644

[issue-644] change type of extension property

---

src/spdx_tools/spdx/parser/tagvalue/parser.py
tests/spdx/parser/tagvalue/test_tag_value_parser.py

With this PR we log an error if the build of a contains relationship fails due to a non-parseable preceding package.
fixes #649

[issue-649] fix TV-parser 

---

src/spdx_tools/spdx/parser/rdf/graph_parsing_functions.py
src/spdx_tools/spdx/parser/rdf/package_parser.py

This PR fixes two minor issues concerning the wrapper methods introduced in #563.
- If the default value is used in `get_value_from_graph` the value doesn't need to be a `URIRef, BNode` or `Literal`, so we shouldn't log an error.
- When parsing the `attribution_texts` in a package we should use the wrapper methods to prevent a warning concerning type mismatches.

fix wrapper methods for parsing the rdf graph

---

src/spdx_tools/spdx/parser/rdf/file_parser.py
src/spdx_tools/spdx/parser/rdf/graph_parsing_functions.py
src/spdx_tools/spdx/parser/rdf/package_parser.py
src/spdx_tools/spdx/parser/rdf/snippet_parser.py
tests/spdx/parser/rdf/data/invalid_documents/file_without_spdx_ids.xml
tests/spdx/parser/rdf/test_file_parser.py
tests/spdx/parser/rdf/test_package_parser.py
tests/spdx/parser/rdf/test_snippet_parser.py

[issue-650] raise ParsingError if elements don't have an SPDXID

---

tests/spdx3/model/ai/test_ai_package.py
tests/spdx3/model/build/test_build.py
tests/spdx3/model/dataset/test_dataset.py
tests/spdx3/model/software/test_file.py
tests/spdx3/model/software/test_package.py
tests/spdx3/model/software/test_sbom.py
tests/spdx3/model/software/test_snippet.py
tests/spdx3/model/software/test_software_dependency_relationship.py
tests/spdx3/model/test_creation_information.py
tests/spdx3/model/test_external_identifier.py
tests/spdx3/model/test_external_map.py
tests/spdx3/model/test_external_reference.py
tests/spdx3/model/test_hash.py
tests/spdx3/model/test_namespace_map.py

The last typeguard update changed the error message text; to ensure this will not break again in the future, this will now not be tested anymore.
Some of the negative tests might look a little pointless right now because in a next step, I will change these to test all properties just like it is already done in [test_element_and_licensing_subclasses.py](https://github.com/spdx/tools-python/blob/6b56465a934fa2ba5b7d04f55e82f6971cb51671/tests/spdx3/model/test_element_and_licensing_subclasses.py).

fix tests after typeguard update

---

src/spdx_tools/spdx3/bump_from_spdx2/creation_information.py
src/spdx_tools/spdx3/bump_from_spdx2/external_document_ref.py
src/spdx_tools/spdx3/bump_from_spdx2/file.py
src/spdx_tools/spdx3/bump_from_spdx2/package.py
tests/spdx3/bump/test_external_document_ref_bump.py

The new conversion follows the description provided in the [migration guide](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.h8bkqwghh9fe).
The test is a little more verbose than necessary because I had some trouble wrapping my head around which field goes where.
Next up is adding external elements to the `imports` list, as also described in the migration guide.
part of #427

[issue-427] fix external document ref bumping

---

src/spdx_tools/spdx3/bump_from_spdx2/creation_info.py

This was a little bug I spotted in the SPDX2->3 conversion.

add spdx2 document comment to spdx3 document instead of creation info

---

examples/spdx2_document_from_scratch.py

Fix the following error/warnings in example script for creating documents from scratch.
```
WARNING:root:did not find the referenced spdx_id "SPDXRef-Document" in the SPDX document
WARNING:root:ValidationContext(spdx_id=None, parent_id=None, element_type=<SpdxElementType.RELATIONSHIP: 13>, full_element=Relationship(spdx_element_id='SPDXRef-Document', relationship_type=<RelationshipType.DESCRIBES: 14>, related_spdx_element_id='SPDXRef-Package', comment=None))
WARNING:root:did not find the referenced spdx_id "SPDXRef-File1" in the SPDX document
WARNING:root:ValidationContext(spdx_id=None, parent_id=None, element_type=<SpdxElementType.RELATIONSHIP: 13>, full_element=Relationship(spdx_element_id='SPDXRef-Package', relationship_type=<RelationshipType.CONTAINS: 6>, …
```

fix(example): fix errors in example file

---

src/spdx_tools/spdx3/bump_from_spdx2/actor.py
src/spdx_tools/spdx3/bump_from_spdx2/annotation.py
src/spdx_tools/spdx3/bump_from_spdx2/creation_info.py
src/spdx_tools/spdx3/bump_from_spdx2/file.py
src/spdx_tools/spdx3/bump_from_spdx2/package.py
src/spdx_tools/spdx3/bump_from_spdx2/relationship.py
src/spdx_tools/spdx3/bump_from_spdx2/snippet.py
src/spdx_tools/spdx3/bump_from_spdx2/spdx_document.py
tests/spdx3/bump/test_actor_bump.py
tests/spdx3/bump/test_file_bump.py
tests/spdx3/bump/test_package_bump.py
tests/spdx3/bump/test_relationship_bump.py
tests/spdx3/bump/test_snippet_bump.py

This fixes a few things that came up during writing the parser:
- use `rootElement` for DESCRIBED Elements
- add the correct URI prefix before the data license
- don't write `CreationInfo` on all Elements (may have to change in the future depending on how we will treat this)
- don't convert licenses (licensing format has yet to be decided on)

Update spdx2 to 3 conversion

---

.github/workflows/check_codestyle.yml
.github/workflows/install_and_test.yml
.github/workflows/prepare_release.yml

Whenever a versioned tag (vX.Y.Z) is pushed, this workflow will build the python wheel, create a new GitHub release for the pushed tag and attach the build output to the release.
This is a first step towards automating our release process. In the future, we may want to directly upload the release to PyPI.
Sample run: https://github.com/fholger/tools-python/actions/runs/5332473607/jobs/9661695249
Sample created release: https://github.com/fholger/tools-python/releases/tag/v0.8.1a4

Create new Github workflow to build a release when a tag is pushed

---

src/spdx_tools/spdx/datetime_conversions.py
tests/spdx/test_datetime_conversions.py

[issue-718] ignore microseconds during datetime conversion to ISO string

---

src/spdx_tools/common/typing/constructor_type_errors.py
src/spdx_tools/spdx/parser/parse_anything.py
src/spdx_tools/spdx/writer/tagvalue/annotation_writer.py
src/spdx_tools/spdx/writer/tagvalue/checksum_writer.py
src/spdx_tools/spdx/writer/tagvalue/creation_info_writer.py
src/spdx_tools/spdx/writer/tagvalue/extracted_licensing_info_writer.py
src/spdx_tools/spdx/writer/tagvalue/file_writer.py
src/spdx_tools/spdx/writer/tagvalue/package_writer.py
src/spdx_tools/spdx/writer/tagvalue/relationship_writer.py
src/spdx_tools/spdx/writer/tagvalue/snippet_writer.py
src/spdx_tools/spdx/writer/tagvalue/tagvalue_writer.py
src/spdx_tools/spdx/writer/tagvalue/tagvalue_writer_helper_functions.py
src/spdx_tools/spdx3/model/__init__.py
src/spdx_tools/spdx3/model/dataset/__init__.py
src/spdx_tools/spdx3/model/software/__init__.py
src/spdx_tools/spdx3/writer/console/__init__.py
src/spdx_tools/spdx3/writer/console/tool_writer.py
tests/spdx/test_cli.py

Inspired by #689 I ran the reuse tool on the code base. It reported a number of missing license and/or copyright headers in our Python source files, which this PR addresses.
Note that reuse also complains about a number of auxiliary files, so this PR does not achieve full compliance on its own.

Add missing license headers in source files

---

.github/workflows/docs.yml

This PR adds a workflow to auto-generate API docs with [pdoc](https://pdoc.dev/docs/pdoc.html) and publish them to GitHub pages.
Actions run: https://github.com/fholger/tools-python/actions/runs/5409859727
Preview: https://frydrych.org/tools-python/spdx_tools.html
While the generated docs do not offer much benefit over browsing the actual code in your IDE, they do provide a searchable and easily navigable web interface to look at the library structure. Given that it costs us virtually nothing to provide it, I believe we might as well have it.
Note: the GitHub pages configuration in the repository settings needs to be updated once to have the GH Pages deployed from a GitHub action instead of branch.

Generate API docs with pdoc

---

src/spdx_tools/spdx/parser/actor_parser.py
tests/spdx/parser/tagvalue/test_annotation_parser.py
tests/spdx/test_actor_parser.py

The new logic follows this rule:
First, split off the `ActorType` part.
Then, if the last character in the string is a closing bracket and there exists a corresponding opening bracket, match everything between these two brackets as `email` and the rest of the string as `name`.
If the the last character is not a closing bracket, match the whole string as `name`.
I also added some more tests for this.
fixes #721

[issue-721] update Actor regex and parsing

---

src/spdx_tools/spdx/spdx_element_utils.py
tests/spdx/test_checksum_calculation.py

also add `calculate_file_checksum()`, as this is needed by the package verification code
fixes #722

[issue-722] add `calculate_package_verification_code()`

---

src/spdx_tools/spdx3/bump_from_spdx2/creation_info.py
src/spdx_tools/spdx3/model/__init__.py
src/spdx_tools/spdx3/model/creation_info.py
src/spdx_tools/spdx3/model/profile_identifier.py
tests/spdx3/bump/test_actor_bump.py
tests/spdx3/fixtures.py
tests/spdx3/model/test_creation_info.py

... to be consistent with the naming in the spec. This makes it easier to generate code working with our model as the naming is deterministic.

SPDX3: rename ProfileIdentifier to ProfileIdentifierType

---

src/spdx_tools/spdx/spdx_element_utils.py
src/spdx_tools/spdx/validation/package_validator.py
tests/spdx/validation/test_package_validator.py

fixes #732
As we cannot infer the type of external elements, we have to assume that external references point to a valid type. Therefore two test cases are now valid.

make "Package CONTAINS Package" valid even when `files_analyzed == False`

---

src/spdx_tools/spdx/writer/rdf/rdf_writer.py

This makes it consistent with the writers of the other formats.

set `validate=True` as default value in the rdf writer 

---

.gitignore
dev/publish_from_tag.sh

This probably would deserve a better placement, description and/or name

add script to publish from tag

---

src/spdx_tools/spdx/parser/jsonlikedict/relationship_parser.py
tests/spdx/parser/all_formats/test_parse_from_file.py
tests/spdx/parser/jsonlikedict/test_dict_parsing_functions.py
tests/spdx/parser/jsonlikedict/test_relationship_parser.py

I ran into long times parsing big SPDX documents that use the `hasFiles` shortcut fields. 
Handling of `hasFiles` field results in the list of all relationships being iterated through for each package. This change moves the creation of `existing_relationships_without_comments` to the top level in `parse_all_relationships`. 
Ideally, it would be nice to use a set for more optimal look-up (but that requires Relationship to be hashable, and probably would like a bit more input on how'd you think that would be better implemented). 
```
before:
python3 src/spdx_tools/spdx/clitools/pyspdxtools.py -i   617.18s user 0.53s system 99% cpu 10:17.96 total
after:
python3 spdx_tools/spdx/clitools/pyspdxtools.py -i  2> /dev/null  316.08s user 0.46s system 99% cpu 5:17.73 total
```

make relationship parsing to be more efficient through precomputation

---

src/spdx_tools/spdx/validation/uri_validators.py
tests/spdx/validation/test_uri_validators.py

Closes #745 
Expands the URL regex used in `validate_download_location` to allow for a [`userinfo`](https://datatracker.ietf.org/doc/html/rfc2396#section-3.2.2) specifier to appear before the hostname. Previously, a value like `git+ssh://git@git.myproject.org/MyProject.git` would fail validation due to the inclusion of the `git@` portion of the URL.
In the URI spec ([RFC2396](https://datatracker.ietf.org/doc/html/rfc2396)), the `userinfo` portion of the server component is defined as follow:
```
userinfo      = *( unreserved | escaped | ";" | ":" | "&" | "=" | "+" | "$" | "," )
unreserved    = alphanum | mark
alphanum      = alpha | digit
alpha         = lowalpha | upalpha
lowalpha      = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" |
"j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | …
```

expand url regex to allow for userinfo

---

src/spdx_tools/spdx/validation/license_expression_validator.py
tests/spdx/validation/test_license_expression_validator.py

[issue-744] implement validation of external license references

---

src/spdx_tools/spdx/validation/uri_validators.py
tests/spdx/validation/test_uri_validators.py

All URLs are valid download locations.
This closes  #761 and #762.

fix(validation): also allow URLs in download locations

---

src/spdx_tools/spdx/parser/json/json_parser.py
src/spdx_tools/spdx/parser/parse_anything.py
src/spdx_tools/spdx/parser/rdf/rdf_parser.py
src/spdx_tools/spdx/parser/tagvalue/tagvalue_parser.py
src/spdx_tools/spdx/parser/xml/xml_parser.py
src/spdx_tools/spdx/parser/yaml/yaml_parser.py
src/spdx_tools/spdx/writer/json/json_writer.py
src/spdx_tools/spdx/writer/tagvalue/tagvalue_writer.py
src/spdx_tools/spdx/writer/xml/xml_writer.py
src/spdx_tools/spdx/writer/yaml/yaml_writer.py
tests/spdx/writer/json/test_json_writer.py

#755
The `rdf_writer` open the file with "wb" and therefore does not support encoding.

implement recommended UTF-8 encoding for reading and writing SPDX files

---

src/spdx_tools/spdx/parser/jsonlikedict/license_expression_parser.py
tests/spdx/data/invalid/spdx-trivy-vmware_log-intelligence-fluentd-sha256_086af034f561f343f633be9d9f9e95f65ae6c61b8ddb2c6755ef5bb25b40f53a.json
tests/spdx/parser/jsonlikedict/test_license_expression_parser.py
tests/spdx/test_cli.py

fix(validation): fix error generation in expression validator

---

.github/workflows/install_and_test.yml
pyproject.toml
src/spdx_tools/spdx/datetime_conversions.py
tests/spdx/test_datetime_conversions.py

Handle timezone-aware datetime objects when writing SPDX.

---

src/spdx_tools/spdx/parser/tagvalue/parser.py
tests/spdx/parser/tagvalue/test_tag_value_parser.py

[issue-771] fix license expression error handling in tag-value parser

---

src/spdx_tools/spdx3/model/software/software_purpose.py

This suggestion is an outcome of a recent discussion in the SPDX FuSa working group where @kestewart suggested that I should report it here directly.
I am implementing SPDX export in the StrictDoc which is a text-based requirements tool. The requirements are stored in text files, and it looks like a new software purpose `REQUIREMENT` would best match the nature of the requirements that I am modelling with SPDX snippets.

spdx3: software_purpose: add REQUIREMENT type

---

src/spdx_tools/spdx/parser/tagvalue/parser.py
tests/spdx/parser/tagvalue/test_annotation_parser.py

[issue-798] fix tag-value parser: parse Tool or Organization as annotator

---

src/spdx_tools/spdx/writer/tagvalue/tagvalue_writer_helper_functions.py
tests/spdx/writer/tagvalue/test_tagvalue_writer_helper_functions.py

[issue-774] fix tag-value output when related_spdx_element_id is "NONE" or "NOASSERTION"

---

src/spdx_tools/spdx/clitools/pyspdxtools.py

[issue-775] catch decoding errors while parsing using the cli tool

---

.github/workflows/check_codestyle.yml
.github/workflows/install_and_test.yml
src/spdx_tools/spdx/parser/jsonlikedict/license_expression_parser.py
tests/spdx/jsonschema/test_file_converter.py
tests/spdx/jsonschema/test_package_converter.py
tests/spdx/jsonschema/test_snippet_converter.py
tests/spdx/model/test_package.py
tests/spdx/parser/jsonlikedict/test_file_parser.py
tests/spdx/parser/jsonlikedict/test_license_expression_parser.py
tests/spdx/parser/jsonlikedict/test_package_parser.py
tests/spdx/parser/jsonlikedict/test_snippet_parser.py
tests/spdx/validation/test_package_validator.py

[issue-806] replace Licensing() with spdx_licensing

---

src/spdx_tools/spdx3/writer/console/console.py
tests/spdx3/writer/tag_value/test_write_document.py

Hello everyone,
This is my first issue to this repository. I am new to SPDX and apologize for possible misunderstanding of the intentions behind the code I am modifying.
I am integrating the SPDX 3.0 export to the StrictDoc tool, see https://github.com/strictdoc-project/strictdoc/issues/1541.
The starting point for this issue is the fact that the `Creation Information` block is suddenly nested with a tab character when I try to populate an `spdx3.*.SpdxDocument` and write to a string buffer. My IDE is set up to ignore tab characters, so the output is displayed as if the indentation level was 1 character wide.
In this MR, the creation info is unindented, and a test is added to demonstrate the behavior I would expect to see.

spdx3: element_writer: switch from tab characters to two spaces

---

.github/workflows/check_codestyle.yml
.github/workflows/install_and_test.yml
.github/workflows/prepare_release.yml
pyproject.toml
src/spdx_tools/common/typing/dataclass_with_properties.py
src/spdx_tools/spdx/parser/jsonlikedict/snippet_parser.py
src/spdx_tools/spdx3/bump_from_spdx2/relationship.py
src/spdx_tools/spdx3/writer/console/__init__.py

fixes #839 
after some updates, this also fixes #844 
ubuntu-latest does not support Python 3.7 anymore.
See https://github.com/actions/runner-images/issues/10636

[issue-839] Drop Python 3.7 support and fix CI pipeline issues

---

src/spdx_tools/spdx/parser/json/json_parser.py
tests/spdx/data/ControlCharacters.spdx.json
tests/spdx/parser/jsonlikedict/test_json_parser.py

[issue-854] Remove some control characters from JSON SPDX
