- spdx/creationinfo.py
- spdx/document.py
- spdx/file.py
- spdx/package.py
- spdx/review.py
- spdx/writers/tagvalue.py
- tests/test_builder.py
Please have a look at the individual commit messages for the details.
> Miscellaneous smaller impovements

- spdx/file.py
- spdx/package.py
- spdx/writers/tagvalue.py
With these changes I"m able to add some very basic SPDX tag/value output format to ScanCode, also see https://github.com/nexB/scancode-toolkit/issues/338.
> Miscellaneous fixes and improvements to make tag/value output work

- spdx/file.py
- spdx/parsers/validations.py
Closes https://github.com/spdx/tools-python/issues/48
@sschuberth @pombredanne @rtgdk Wanna review this one ?
> Use isinstance instead of `type(..) in [..]` #48

- spdx/parsers/tagvalue.py
> Removed redundancy in spdx/parsers/tagvalue.py

- .gitignore
PR for issue #41 
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>
> Update .gitignore file #41

- spdx/annotation.py
- spdx/creationinfo.py
- spdx/document.py
- spdx/file.py
- spdx/package.py
- spdx/parsers/rdf.py
- spdx/parsers/tagvalue.py
- spdx/review.py
- spdx/writers/rdf.py
- spdx/writers/tagvalue.py
- tests/data/doc_write/rdf-simple-plus.json
- tests/data/doc_write/rdf-simple.json
- tests/data/doc_write/tv-simple-plus.tv
- tests/data/doc_write/tv-simple.tv
- tests/test_conversion.py
- tests/test_document.py
We now return messages from each `validation` function
instead of modifying lists in place.
Closes https://github.com/spdx/tools-python/issues/50
Review needed @sschuberth @pombredanne @rtgdk
> Return messages instead of modifying list #50

- README.md
Describes the steps to follow whenever we have to make some changes to the code or add some new features
Signed-off-by: Krys Nuvadga
> Added Development process

- CONTRIBUTING.MD
I've included the work done by @avirlrma in #33 with the changes requested by @pombredanne.  I'll be around most nights of this week for any edits as needed.
<details open><summary>Sign-off</summary>
I sign off on the DCO.
</details>
> Added CONTRIBUTING.md with the changes requested in PR #33

- setup.py
Check our demo on a test instance of PyPi : https://test.pypi.org/project/spdx-tools
> Add description that is missing on PyPi

- data/SPDXRdfExample.rdf
- data/SPDXSimpleTag.tag
- data/SPDXTagExample.tag
- spdx/package.py
- spdx/parsers/lexers/tagvalue.py
- spdx/parsers/rdf.py
- spdx/parsers/rdfbuilders.py
- spdx/parsers/tagvalue.py
- spdx/parsers/tagvaluebuilders.py
- spdx/parsers/validations.py
- spdx/writers/rdf.py
- spdx/writers/tagvalue.py
- tests/data/doc_write/rdf-simple-plus.json
- tests/data/doc_write/rdf-simple.json
- tests/data/doc_write/tv-simple-plus.tv
- tests/data/doc_write/tv-simple.tv
- tests/test_builder.py
- tests/test_document.py
- tests/test_tag_value_parser.py
This is to upgrade the 'Package' class to the SPDX 2.1 specification 
This is #72 from @yash-nisar rebased by @xavierfigueroav
> Upgrade the 'Package' class to the SPDX 2.1 specification 

- README.md
WIP for:
Signed-off-by: Kyle Altendorf <sda@fstab.net>
> [WIP] Add --signoff to README.md `git commit` references

- .circleci/config.yml
- CHANGELOG.rst
- README.md
- appveyor.yml
- examples/pp_rdf.py
- setup.py
- spdx/document.py
- spdx/parsers/lexers/tagvalue.py
- spdx/writers/tagvalue.py
- tests/data/doc_write/tv-simple-plus.tv
- tests/data/doc_write/tv-simple.tv
- tests/test_error_messages.py
- tests/test_jsonyamlxml_parser.py
- tests/test_parse_anything.py
- tests/test_rdf_parser.py
- tests/test_write_anything.py
- tests/utils_test.py
This PR is the release prep.
This contains:
- drop Python 2
- various bug fixes
- adopt SPDX 2.2
- several other improvements accumulated since the last version.
> Create release 0.7.0

- .circleci/config.yml
Signed-off-by: Rodney Richardson <rodney.richardson@cambridgeconsultants.com>
Fixes #202
> Bump xcode from 9.4.1 to 10.3.0

- README.md
Signed-off-by: HARDIK <hardik@HARDIKs-MacBook-Pro.local>
> Corrected the documentation in README.md

- .circleci/config.yml
Signed-off-by: Jeff Licquia <licquia@linuxfoundation.org>
> Bump xcode to 13.0.0 for the Mac tests.

- spdx/cli_tools/convertor.py
- tests/test_cli_convertor.py
fixes issue #152 
I decided to extract a method to get the infile and outfile from the given input arguments to also add a TestCase for this functionality.
> [issue-152] fix cli convertor and add testcase

- data/SPDXRdfExample.rdf
> [issue-230] fix provided example to be valid

- spdx/writers/tagvalue.py
- tests/data/doc_write/tv-mini.tv
- tests/data/doc_write/tv-simple-plus.tv
- tests/data/doc_write/tv-simple.tv
> [issue-238] group annotations, reviews and relationships under one headline

- spdx/file.py
- spdx/package.py
- spdx/snippet.py
This takes over from https://github.com/spdx/tools-python/pull/132 due to sign-off issues
fixes #88
> New implementation of `has_optional_field`

- setup.py
- spdx/writers/rdf.py
- tests/test_rdf_writer.py
Taken over from the original PR by @quaresmajose: https://github.com/spdx/tools-python/pull/199
Signed-off-by: Nicolaus Weidner <nicolaus.weidner@tngtech.com>
> writers[rdf]: add an option to pass create_doc write

- README.md
- spdx/creationinfo.py
- spdx/document.py
- spdx/package.py
- spdx/parsers/jsonyamlxml.py
- spdx/parsers/loggers.py
- spdx/parsers/parse_anything.py
- spdx/parsers/rdf.py
- spdx/parsers/tagvalue.py
- spdx/parsers/tagvaluebuilders.py
- spdx/relationship.py
- spdx/snippet.py
- spdx/tv_to_rdf.py
- spdx/utils.py
- spdx/writers/rdf.py
Signed-off-by: John Vandenberg <jayvdb@gmail.com>
> Fix spelling and some docstring improvements

- spdx/parsers/tagvaluebuilders.py
- tests/test_tag_value_parser.py
> [issue-281] fix parsing of file attribution text and add test

- spdx/writers/tagvalue.py
> [issue-272] make properties in tv-writer optional

- spdx/relationship.py
> [issue-301] add new relationship_types

- spdx/document.py
- spdx/writers/rdf.py
- tests/data/doc_write/rdf-mini.json
- tests/data/doc_write/tv-mini.tv
- tests/test_document.py
> [issue-239] make packages in document optional

- spdx/parsers/jsonyamlxml.py
> [issue-312] fix typo in attribution text parsing

- spdx/cli_tools/parser.py
- spdx/writers/jsonyamlxml.py
> [issue-239] make packages and files in cli parser and jsonyamlxml-writer optional

- src/model/document.py
- src/model/extracted_licensing_info.py
- src/model/file.py
- src/model/package.py
- src/model/snippet.py
> refactor some code and shorten name of external_document_references

- examples/tv_to_rdf.py
- examples/write_tv.py
- spdx/review.py
> fix example scripts

- spdx/checksum.py
> [issue-185] fix bug in checksum

- spdx/parsers/jsonyamlxml.py
> terminate parsing of relationship if one of the ids isn't a string

- README.md
> [issue-335] update readme for the 0.7.0 release

- spdx/file.py
- spdx/package.py
Fixes https://github.com/spdx/tools-python/issues/342
> [issue-342] fix get_checksum KeyErrors

- pyproject.toml
- src/model/actor.py
- src/model/annotation.py
- src/model/checksum.py
- src/model/dataclass_with_properties.py
- src/model/document.py
- src/model/external_document_ref.py
- src/model/extracted_licensing_info.py
- src/model/file.py
- src/model/license_expression.py
- src/model/package.py
- src/model/relationship.py
- src/model/snippet.py
- src/model/spdx_no_assertion.py
- src/model/spdx_none.py
- tests/model/test_actor.py
- tests/model/test_annotation.py
- tests/model/test_checksum.py
- tests/model/test_creation_info.py
- tests/model/test_document.py
- tests/model/test_external_document_ref.py
- tests/model/test_external_package_reference.py
- tests/model/test_extracted_licensing_info.py
- tests/model/test_file.py
- tests/model/test_package.py
- tests/model/test_package_verification_code.py
- tests/model/test_relationship.py
- tests/model/test_snippet.py
Fixes https://github.com/spdx/tools-python/issues/321
> [issue-321] introduce dataclass (with properties) and typeguard

- src/model/document.py
- src/model/package.py
- tests/model/test_creation_info.py
- tests/model/test_document.py
- tests/model/test_external_package_reference.py
- tests/model/test_package.py
> [issue-306] refactor creation info (and shorten external package ref)

- src/model/actor.py
- src/model/annotation.py
- src/model/checksum.py
- src/model/document.py
- src/model/external_document_ref.py
- src/model/extracted_licensing_info.py
- src/model/file.py
- src/model/package.py
- src/model/relationship.py
- src/model/snippet.py
- tests/model/test_annotation.py
> change annotator type to Actor and clean imports

- src/model/typing/dataclass_with_properties.py
- src/model/typing/type_checks.py
> [issue-348] refine error messages in getters and setters directly

- src/model/annotation.py
> [fix] change annotator type to actor in constructor

- CHANGELOG.md
Signed-off-by: Nicolaus Weidner <nicolaus.weidner@tngtech.com>
> [hotfix] Add 0.7.0 release date and additional contributors

- src/model/file.py
> [fix] change constructor type of file.license_info_in_file

- src/model/document.py
- src/model/extracted_licensing_info.py
- src/model/file.py
- src/model/package.py
- src/model/snippet.py
- tests/model/test_creation_info.py
- tests/model/test_document.py
> [issue-355] don't allow arbitrary falsey values for optional lists in constructors

- src/model/external_document_ref.py
- tests/model/test_external_document_ref.py
> [issue-363] rework ExternalDocumentRef

- src/model/typing/dataclass_with_properties.py
> add class name to error messages from setter/ getter

- src/parser/json/actor_parser.py
- src/parser/json/annotation_parser.py
- src/parser/json/checksum_parser.py
- src/parser/json/dict_parsing_functions.py
- src/parser/json/file_parser.py
- src/parser/json/package_parser.py
- src/validation/relationship_validator.py
- tests/parser/test_extracted_licensing_info_parser.py
- tests/parser/test_json_parser.py
- tests/validation/test_external_document_ref_validator.py
> [format] delete unused imports

- src/writer/tagvalue/relationship_writer.py
as this can also be NONE or NOASSERTION
> convert related_spdx_element_id to str in tv writer

- src/spdx/parser/jsonlikedict/dict_parsing_functions.py
- src/spdx/parser/jsonlikedict/relationship_parser.py
- tests/parser/json/test_json_parser.py
- tests/parser/jsonlikedict/test_relationship_parser.py
> [issue-400] ignore duplicated relationships while parsing

- src/spdx3/model/annotation.py
- src/spdx3/model/bom.py
- src/spdx3/model/bundle.py
- src/spdx3/model/relationship.py
- src/spdx3/model/software/sbom.py
- src/spdx3/model/spdx_collection.py
- src/spdx3/model/spdx_document.py
- src/spdx3/spdx_id_map.py
- tests/spdx3/model/software/test_sbom.py
- tests/spdx3/model/test_annotation.py
- tests/spdx3/model/test_bom.py
- tests/spdx3/model/test_bundle.py
- tests/spdx3/model/test_relationship.py
- tests/spdx3/model/test_spdx_document.py
also replace all `Element` references with `str` (`spdx_id`s)
> add SpdxIdMap to easily collect and reference all current elements

- src/spdx3/bump_from_spdx2/annotation.py
- src/spdx3/bump_from_spdx2/creation_information.py
- src/spdx3/bump_from_spdx2/file.py
- src/spdx3/bump_from_spdx2/message.py
- src/spdx3/bump_from_spdx2/package.py
- src/spdx3/bump_from_spdx2/snippet.py
- src/spdx3/bump_from_spdx2/spdx_document.py
- src/spdx3/clitools/pyspdxtools3.py
Just some minor cleanup of stderr vs stdout.
> do some cleanup

- src/spdx/validation/file_validator.py
- tests/spdx/validation/test_file_validator.py
> [issue-443] change file name validation logic

- pyproject.toml
- spdx/parsers/validations.py
> [issue-451] use uritools.isabsuri for namespace validation

- CONTRIBUTING.md
..in the contributing guideline
fixes #468 
> [issue-468] add a step to fork the repository

- .github/workflows/install_and_test.yml
With this PR we add a GitHub Actions workflow to the main branch to also test installation on windows.
> add GitHub Actions workflow

- README.md
- src/spdx/jsonschema/file_converter.py
- src/spdx/model/file.py
- src/spdx/parser/jsonlikedict/file_parser.py
- src/spdx/parser/rdf/file_parser.py
- src/spdx/parser/tagvalue/parser.py
- src/spdx/writer/rdf/file_writer.py
- src/spdx/writer/tagvalue/file_writer.py
- tests/spdx/fixtures.py
- tests/spdx/jsonschema/test_file_converter.py
- tests/spdx/model/test_file.py
- tests/spdx/parser/jsonlikedict/test_file_parser.py
- tests/spdx/parser/rdf/test_file_parser.py
- tests/spdx/parser/tagvalue/test_file_parser.py
> [issue-518] rename file_type to file_types

- spdx/writers/rdf.py
- tests/data/doc_write/rdf-simple-plus.json
- tests/data/doc_write/rdf-simple.json
- tests/test_rdf_writer.py
> [issue-514] fix writing of multiple packages to rdf files

- CHANGELOG.md
> update changelog for v0.7.1

- .github/dependabot.yml
> Enable dependabot version checking

- src/spdx3/bump_from_spdx2/actor.py
- src/spdx3/bump_from_spdx2/annotation.py
- src/spdx3/bump_from_spdx2/creation_information.py
- src/spdx3/bump_from_spdx2/file.py
- src/spdx3/bump_from_spdx2/package.py
- src/spdx3/bump_from_spdx2/relationship.py
- src/spdx3/bump_from_spdx2/snippet.py
- src/spdx3/bump_from_spdx2/spdx_document.py
- tests/spdx3/bump/test_actor_bump.py
- tests/spdx3/bump/test_file_bump.py
- tests/spdx3/bump/test_package_bump.py
- tests/spdx3/bump/test_snippet_bump.py
- tests/spdx3/bump/test_spdx_document_bump.py
> Add doc namespace to spdx ids during 2->3 conversion

- src/spdx3/bump_from_spdx2/package.py
- src/spdx3/model/software/package.py
- src/spdx3/writer/console/software/package_writer.py
- tests/spdx3/bump/test_package_bump.py
- tests/spdx3/model/software/test_package.py
> [issue-427] add bumping of ExternalPackageRef

- src/spdx/writer/rdf/relationship_writer.py
> [issue-580] RDF: don't output relationship comment if there is none

- src/spdx3/README.md
- src/spdx3/bump_from_spdx2/package.py
- src/spdx3/model/software/package.py
- tests/spdx3/bump/test_package_bump.py
- tests/spdx3/model/software/test_package.py
> [issue-426] add `source_info` to `Package`

- tests/spdx/data/SPDXLite.spdx
- tests/spdx/validation/test_document_validator.py
> [issue-375] add validation test for SPDX Lite

- src/spdx_tools/spdx3/model/dataset/__init__.py
- src/spdx_tools/spdx3/model/dataset/dataset.py
- tests/spdx3/model/dataset/test_dataset.py
> [issue-426] add Dataset class

- src/spdx_tools/spdx3/model/dataset/dataset.py
- tests/spdx3/model/dataset/test_dataset.py
Oversight during #604: Dataset is a subclass of package.
> [issue-426] make Dataset a subclass of Package

- src/spdx_tools/spdx/model/__init__.py
Was forgotten in #600, to implement #511.
> [issue-511] add license header

- src/spdx_tools/spdx3/writer/console/dataset/dataset_writer.py
- src/spdx_tools/spdx3/writer/console/payload_writer.py
also add AI, Dataset and Build to `payload_writer.py`
part of #434
> [issue-434] add writer for Dataset

- src/spdx_tools/spdx3/writer/console/ai/ai_package_writer.py
- src/spdx_tools/spdx3/writer/console/annotation_writer.py
- src/spdx_tools/spdx3/writer/console/artifact_writer.py
- src/spdx_tools/spdx3/writer/console/build/build_writer.py
- src/spdx_tools/spdx3/writer/console/console.py
- src/spdx_tools/spdx3/writer/console/creation_information_writer.py
- src/spdx_tools/spdx3/writer/console/dataset/dataset_writer.py
- src/spdx_tools/spdx3/writer/console/element_writer.py
- src/spdx_tools/spdx3/writer/console/external_identifier_writer.py
- src/spdx_tools/spdx3/writer/console/external_reference_writer.py
- src/spdx_tools/spdx3/writer/console/hash_writer.py
- src/spdx_tools/spdx3/writer/console/namespace_map_writer.py
- src/spdx_tools/spdx3/writer/console/relationship_writer.py
- src/spdx_tools/spdx3/writer/console/software/file_writer.py
- src/spdx_tools/spdx3/writer/console/software/package_writer.py
- src/spdx_tools/spdx3/writer/console/software/snippet_writer.py
Tested with `AIPackage`
part of #434
> [issue-434] refactor debug writers

- src/spdx_tools/spdx3/bump_from_spdx2/annotation.py
- src/spdx_tools/spdx3/bump_from_spdx2/creation_information.py
- src/spdx_tools/spdx3/bump_from_spdx2/file.py
- src/spdx_tools/spdx3/bump_from_spdx2/package.py
- src/spdx_tools/spdx3/bump_from_spdx2/snippet.py
I added the links to get a better understanding and overview of the current state of conversion SPDX 2 -> 3.
> add links for GH issues tracking missing conversion rules

- src/spdx_tools/spdx3/model/software/file.py
- src/spdx_tools/spdx3/model/software/package.py
- tests/spdx3/model/software/test_file.py
- tests/spdx3/model/software/test_package.py
according to [#170](https://github.com/spdx/spdx-3-model/pull/170)
> [issue_426] make name mandatory for package and file

- src/spdx_tools/spdx3/model/__init__.py
- src/spdx_tools/spdx3/model/lifecycle_scoped_relationship.py
- src/spdx_tools/spdx3/model/relationship.py
- src/spdx_tools/spdx3/model/software/__init__.py
- src/spdx_tools/spdx3/model/software/software_dependency_relationship.py
- src/spdx_tools/spdx3/writer/console/lifecycle_scoped_relationship_writer.py
- src/spdx_tools/spdx3/writer/console/relationship_writer.py
- src/spdx_tools/spdx3/writer/console/software/software_dependency_relationship_writer.py
- tests/spdx3/model/software/test_software_dependency_relationship.py
- tests/spdx3/model/test_lifecycle_scoped_relationship.py
> [issue-426] add LifecycleScopedRelationship and SoftwareDependencyRelationship

- src/spdx_tools/spdx3/README.md
- src/spdx_tools/spdx3/model/ai/ai_package.py
- src/spdx_tools/spdx3/model/dataset/dataset.py
- src/spdx_tools/spdx3/model/external_identifier.py
- src/spdx_tools/spdx3/model/hash.py
- tests/spdx3/model/ai/test_ai_package.py
- tests/spdx3/model/dataset/test_dataset.py
- tests/spdx3/model/test_external_identifier.py
- adapt some field names to use singular
- add identifier_locator and issuing_authority to ExternalIdentifier
I went through all changes since the last tagged commit and updated the implementation.
> Update model according to recent changes in spdx-3-model

- src/spdx_tools/spdx3/model/external_reference.py
> Issue #426: Update `ExternalReferenceType`

- src/spdx_tools/spdx3/model/lifecycle_scoped_relationship.py
- src/spdx_tools/spdx3/model/relationship.py
- src/spdx_tools/spdx3/model/software/software_dependency_relationship.py
- tests/spdx3/model/software/test_software_dependency_relationship.py
- tests/spdx3/model/test_lifecycle_scoped_relationship.py
- tests/spdx3/model/test_relationship.py
adds `start_time` and `end_time` properties and new `RelationshipType` entries.
part of #426
> Issue #426: update Relationship and RelationshipType

- src/spdx_tools/spdx3/model/licensing/__init__.py
- src/spdx_tools/spdx3/model/licensing/any_license_info.py
- src/spdx_tools/spdx3/model/licensing/conjunctive_license_set.py
- src/spdx_tools/spdx3/model/licensing/custom_license.py
- src/spdx_tools/spdx3/model/licensing/custom_license_addition.py
- src/spdx_tools/spdx3/model/licensing/disjunctive_license_set.py
- src/spdx_tools/spdx3/model/licensing/license.py
- src/spdx_tools/spdx3/model/licensing/license_addition.py
- src/spdx_tools/spdx3/model/licensing/license_field.py
- src/spdx_tools/spdx3/model/licensing/listed_license.py
- src/spdx_tools/spdx3/model/licensing/listed_license_exception.py
- src/spdx_tools/spdx3/model/licensing/no_assertion_license.py
- src/spdx_tools/spdx3/model/licensing/none_license.py
- src/spdx_tools/spdx3/model/licensing/or_later_operator.py
- src/spdx_tools/spdx3/model/licensing/with_addition_operator.py
> [issue-426] add licensing profile

- src/spdx_tools/spdx3/model/licensing/__init__.py
- src/spdx_tools/spdx3/model/licensing/any_license_info.py
- src/spdx_tools/spdx3/model/licensing/license.py
- src/spdx_tools/spdx3/model/licensing/license_field.py
- src/spdx_tools/spdx3/model/licensing/no_assertion_license.py
- src/spdx_tools/spdx3/model/licensing/none_license.py
- update import paths in __init__.py
- remove dataclass annotation for classes without fields
> fix licensing profile

- src/spdx_tools/spdx3/bump_from_spdx2/package.py
- src/spdx_tools/spdx3/model/ai/ai_package.py
- src/spdx_tools/spdx3/model/dataset/dataset.py
- src/spdx_tools/spdx3/model/software/file.py
- src/spdx_tools/spdx3/model/software/package.py
- src/spdx_tools/spdx3/model/software/snippet.py
- src/spdx_tools/spdx3/model/software/software_artifact.py
- tests/spdx3/model/ai/test_ai_package.py
- tests/spdx3/model/dataset/test_dataset.py
- tests/spdx3/model/software/test_file.py
- tests/spdx3/model/software/test_package.py
- tests/spdx3/model/software/test_snippet.py
> [issue-426] add SoftwareArtifact

- src/spdx_tools/spdx3/model/software/__init__.py
- src/spdx_tools/spdx3/model/software/sbom.py
- tests/spdx3/model/software/test_sbom.py
> [issue-426] add SBOMType

- src/spdx_tools/spdx3/clitools/pyspdxtools3.py
- src/spdx_tools/spdx3/writer/json_ld/json_ld_converter.py
- src/spdx_tools/spdx3/writer/json_ld/json_ld_writer.py
- src/spdx_tools/spdx3/writer/json_ld/owl_to_context.py
- tests/spdx3/validation/json_ld/test_shacl_validation.py
- tests/spdx3/writer/json_ld/test_json_ld_writer.py
This is only a prototyped serialization for json ld.
> add cli functionality to use json ld serialization

- tests/spdx3/fixtures.py
This makes the existing Core fixtures more consistent, uses URIs where appropriate and fixes the handling of lists as standard arguments.
part of #432
> [issue-432] rework SPDX3 Core fixtures

- src/spdx_tools/spdx3/model/security/cvss_v2_vuln_assessment_relationship.py
- src/spdx_tools/spdx3/model/security/cvss_v3_vuln_assessment_relationship.py
- src/spdx_tools/spdx3/model/security/ssvc_vuln_assessment_relationship.py
- src/spdx_tools/spdx3/model/security/vex_not_affected_vuln_assessment_relationship.py
- tests/spdx3/fixtures.py
- tests/spdx3/model/test_element_subclasses.py
also fixed some minor bugs in the class definitions.
part of #432 and #426
> Add security profile tests and fixtures

- tests/spdx3/fixtures.py
- tests/spdx3/model/licensing/test_conjunctive_license_set.py
- tests/spdx3/model/licensing/test_disjunctive_license_set.py
- tests/spdx3/model/licensing/test_or_later_operator.py
- tests/spdx3/model/licensing/test_with_addition_operator.py
- tests/spdx3/model/test_element_and_licensing_subclasses.py
> [issue-432] add licensing fixtures and tests

- tests/spdx3/model/model_test_utils.py
- tests/spdx3/model/test_creation_information.py
- tests/spdx3/model/test_element_and_licensing_subclasses.py
- tests/spdx3/model/test_external_identifier.py
- tests/spdx3/model/test_external_map.py
- tests/spdx3/model/test_external_reference.py
- tests/spdx3/model/test_hash.py
- tests/spdx3/model/test_namespace_map.py
part of #432
This also tests that every property is getting a value in the fixtures.
> [issue-432] use fixtures in initialization tests

- tests/spdx3/fixtures.py
> Add fixture dictionaries for software profile

- src/spdx_tools/spdx/spdx_element_utils.py
- src/spdx_tools/spdx3/bump_from_spdx2/external_element_utils.py
- src/spdx_tools/spdx3/bump_from_spdx2/file.py
- src/spdx_tools/spdx3/bump_from_spdx2/package.py
- src/spdx_tools/spdx3/bump_from_spdx2/snippet.py
- src/spdx_tools/spdx3/bump_from_spdx2/spdx_document.py
- src/spdx_tools/spdx3/model/external_map.py
- tests/spdx3/bump/test_external_element_bump.py
- tests/spdx3/bump/test_file_bump.py
- tests/spdx3/bump/test_package_bump.py
- tests/spdx3/bump/test_snippet_bump.py
- tests/spdx3/fixtures.py
- tests/spdx3/model/test_external_map.py
according to the [migration guide](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.h8bkqwghh9fe)
part of #427
> [issue-427] implement bumping of external SPDX elements

- tests/spdx3/fixtures.py
> Add fixture dictionary for Dataset profile

- tests/spdx3/fixtures.py
> Add fixture dict. for ai_package profile

- src/spdx_tools/spdx3/model/dataset/dataset.py
- src/spdx_tools/spdx3/writer/console/dataset/dataset_writer.py
> fix dataset sensor property

- tests/spdx/examples/test_spdx2_document_from_scratch.py
> [issue-692] add test for the example code

- src/spdx_tools/spdx/writer/tagvalue/tagvalue_writer.py
- tests/spdx/writer/tagvalue/test_tagvalue_writer.py
fixes #693
The problem was that a file belonging to multiple packages would be written out multiple times. This has been fixed. Now, the file is written only for the first package, all other occurrences are modeled as `CONTAINS` relationships.
> [issue-693] TV writer: fix for same file in multiple packages

- src/spdx_tools/spdx3/bump_from_spdx2/creation_info.py
- src/spdx_tools/spdx3/model/creation_info.py
- tests/spdx3/bump/test_actor_bump.py
- tests/spdx3/fixtures.py
- tests/spdx3/model/test_creation_info.py
> [issue-426] update model: make `created_using` optional

- .github/workflows/integration_test.yml
- tests/spdx/data/circleConversionTestInitialDocument.json
> [issue-413] add workflow for circle conversion integration test

- examples/spdx2_convert_format.py
- examples/spdx2_convert_to_spdx3.py
- examples/spdx2_generate_graph.py
- examples/spdx2_parse_file.py
- src/spdx_tools/spdx3/bump_from_spdx2/creation_info.py
- src/spdx_tools/spdx3/bump_from_spdx2/package.py
- tests/spdx/examples/test_examples.py
This PR adds a few more examples of how to use certain features of the library that are mentioned in the README.
> Add more usage examples for the SPDX2 part of the library

- CHANGELOG.md
- README.md
Updates the readme and changelog in preparation for the v0.8.0 release candidate.
> Prepare readme and changelog for v0.8.0rc1 release

- DOCUMENTATION.md
> add documentation on the code architecture

- src/spdx_tools/spdx/clitools/pyspdxtools.py
- tests/spdx/test_cli.py
> [issue-773] shorten output of FileNotFoundError when called via the CLI

- src/spdx_tools/spdx/validation/uri_validators.py
- tests/spdx/validation/test_uri_validators.py
This is a fix for https://github.com/spdx/tools-python/issues/825
> downloadLocation URIs not case sensitive
